version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the nginx.conf file to the container
    depends_on:
      - web1
      - web2
      - web3

  web1:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production

  web2:
    build: .
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=production

  web3:
    build: .
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=production



    
